### ISSUE TITLE
Deploying ArbSys and ArbRetryableTx using ganache

### ISSUE THREAD

**Issue by anishnaik** [OffchainLabs/arbitrum-sdk#110]
Is there a way to deploy `ArbSys` and `ArbRetryableTx` at the same addresses that are used in production while using Ganache?

`ArbSys` address: `0x0000000000000000000000000000000000000064`
`ArbRetryableTx` address: `0x000000000000000000000000000000000000006E`

More generally, if you can point to some test or deployment script in this repo or the Arbitrum monorepo, that would be helpful.

**Comment by anishnaik** [comment]
Closing this since this effectively requires a private key and it seems like the modified geth code just creates a mapping b/w address and implementation.

**Comment by yahgwai** [comment]
Hi @anishnaik, yes we currently don't support testing via hardhat or ganache. However, just letting you know that we are looking into it, and hopefully we'll be able to provide something in the future.
