### ISSUE TITLE
`EthBridger.depositTo` uses the wrong `createRetryableTicket` method

### ISSUE THREAD

**Issue by tadad** [OffchainLabs/arbitrum-sdk#534]
This line [here](https://github.com/OffchainLabs/arbitrum-sdk/blob/main/src/lib/message/ParentToChildMessageCreator.ts#L159) should leaves out the case where the `nativeToken === constants.zeroAddress` leading to cases where it tries to call `IERC20Inbox.createRetryableTicket` instead of `IInbox.createRetryableTicket`

**Comment by spsjvc** [comment]
Fixed in https://github.com/OffchainLabs/arbitrum-sdk/pull/541 and released in [v3.7.1](https://github.com/OffchainLabs/arbitrum-sdk/releases/tag/v3.7.1) and [v4.0.2](https://github.com/OffchainLabs/arbitrum-sdk/releases/tag/v4.0.2).
